name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase: '^4.1.0'
  firebase_auth: '0.2.3'
  firebase_database: '0.1.0'

flutter:
  uses-material-design: true
