name: yaio
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl:
  google_sign_in:
  firebase_auth:
  firebase_database:
  firebase_messaging:
  shared_preferences:
  charts_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: asset/fonts/raleway/Raleway-Regular.ttf
        - asset: asset/fonts/raleway/Raleway-Medium.ttf
        - asset: asset/fonts/raleway/Raleway-SemiBold.ttf
          style: italic
