name: yaio
description: A new Flutter project.
version: 0.4.2+16
dependencies:
  flutter:
    sdk: flutter
  intl:
  google_sign_in:
  firebase_auth:
  firebase_database:
  firebase_messaging:
  shared_preferences:
  charts_flutter:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
